export const POPULAR_MOVIES = `POPULAR_MOVIES`
export const RATED_MOVIES = `RATED_MOVIES`
export const NOW_PLAYING = `NOW_PLAYING`
export const SEARCHED_QUERY = `SEARCHED_QUERY`
export const SWITCH_TAB = `SWITCH_TAB`
export const LOADING = `LOADING`
export const APIERROR = `APIERROR`
export const NORESULTSFOUND = `NORESULTSFOUND`



